/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package comp3111.lab8.repo1;

public class Library {
	public static void main(String arg[]) {
		Library lib = new Library();
		if(lib.someLibraryMethod())
			System.out.println("Hey this is idk what this is.");
			
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
